### ISSUE TITLE
Translating excerpt more

### ISSUE THREAD

**Issue by justintadlock** [samikeijonen/checathlon#10]
In `inc/functions-filters.php`, the excerpt more filter is a bit odd at first glance:

```
/* Translators: The %s is mark after excerpt. */
$more = sprintf( esc_attr__( '%s', 'checathlon' ), '&hellip;' );
```

The `%s` itself can't be translated.  However, I suppose a translator could simply use different text or add text next to the `%s`.  I like to add the `&hellip;` inside of the translation so that it can be changed.

I wanted to bring this up to get your thoughts and make sure it was intentional.

**Comment by samikeijonen** [comment]
That does feel weird. Will update to have it like `esc_attr__( '&hellip;', 'checathlon' )`.

**Comment by samikeijonen** [comment]
@justintadlock was this what you ment: 8e4680c98222f31ed5e2a5a28556c277a9a3e3f2.

**Comment by justintadlock** [comment]
Yes, that's it.

Also, that should use `esc_html` rather than `esc_attr`.  Just picked up on that.

**Comment by samikeijonen** [comment]
I'll change it tomorrow. Bed time around here.

**Comment by samikeijonen** [comment]
Changed in commit 05fd922ecd190a5c654cbd8899c6d46321ac40e3.
