### ISSUE TITLE
Styling: wp_link_pages()

### ISSUE THREAD

**Issue by justintadlock** [samikeijonen/checathlon#13]
With the attention to detail that you gave to other navigation, this seems to be lacking and kind of plain.  It might be something you overlooked.

![wp-link-pages](https://cloud.githubusercontent.com/assets/1816309/20850614/ac473b0c-b8a1-11e6-8a71-abb120593287.png)

**Comment by samikeijonen** [comment]
Oh forgot those, should be the same as post navigation.
