### ISSUE TITLE
Styling issue with List Items in Widget

### ISSUE THREAD

**Issue by sakinshrestha** [samikeijonen/checathlon#2]
* There is no margin/bullets/numbering to separate "list item with long title" and "new list item" in widget. 
![list-items-margin-issue-widget](https://cloud.githubusercontent.com/assets/9452203/20801905/58060b3e-b7b8-11e6-91d0-247b2a20982f.png)

**Comment by samikeijonen** [comment]
I'll probably add bottom border or regular bullet for it.

**Comment by sakinshrestha** [comment]
Yes, that will do the job.
