### ISSUE TITLE
Comment section location issue

### ISSUE THREAD

**Issue by sakinshrestha** [samikeijonen/checathlon#6]
* I feel little odd that the comment section comes only after the sidebar and not just below the page/post content. This is creating UI issue. Like when I have long sidebar widget and short content. Then I need to scroll all the way down to footer to post the comment.

**Comment by samikeijonen** [comment]
This is hard one. I totally get that UI issue but I'll probably take that risk.

**Comment by samikeijonen** [comment]
Going to close this even if I know this might be a problem in some cases.
