### ISSUE TITLE
Search/Replace fail

### ISSUE THREAD

**Issue by justintadlock** [samikeijonen/checathlon#9]
I noticed this in `inc/functions-scripts.php` where you were copying over the license from Hybrid Core:

```
 * @copyright Copyright (c) 2008 - 2015, Justin Tadlock
 * @link      http://themechecathlon.com/checathlon-core
```

If you're like me, you probably do a file search/replace with a lot of your themes. I've done this a lot of times. :smile:

**Comment by samikeijonen** [comment]
Didn't you know I have `checathlon-core` :). I'll fix that, like you said it's copy/paste/search/replace mistake.
